### ISSUE TITLE
Caching of API Keys on Router Nodes

### ISSUE THREAD

**Issue by darylrobbins** [NREL/api-umbrella#111]
It appears that the Gatekeeper is checking with MongoDB on every request to see if a particular key is valid. This would seem like something that should be cached temporarily in Redis on each router node to reduce request latency and the load on MongoDB. Even caching for a minute or so would make a huge difference for a high volume API. Thoughts?

**Comment by GUI** [comment]
Yeah, this is one of those optimizations that's been on my mind for a while, but it's never quite happened. This has already been implemented in the experimental Lua revamp (https://github.com/NREL/api-umbrella/issues/86), and it's actually a bit better there, since the cache is in local shared memory (rather than requiring a connection to Redis). That being said, we could certainly look at this kind of caching in the current Node implementation depending on the timeframe of the Lua work.

**Comment by GUI** [comment]
Key caching is performed in the v0.9 release.
