### ISSUE TITLE
Offline login?

### ISSUE THREAD

**Issue by toringe** [NREL/api-umbrella#124]
How do I login to the admin interface when API Umbrella is installed on a machine without internet access? Is there no local user authorization available?

**Comment by GUI** [comment]
@toringe: Sorry for the delay in responding. Currently there is no local database for admin authentication. This has come up before, though. Out of curiosity, would you be interested in an authentication mechanism that could hook into some other internal-only authentication system (eg, via something like SAML, CAS, LDAP, ActiveDirectory, etc)? Or would you prefer to have the API Umbrella admin have it's own standalone user database?

**Comment by toringe** [comment]
Hi Nick.

I am no advocate of local user dbs,  but an operations principle I like to
adhere to is to have no external/third party dependency on root or admin
accounts.

However,  LDAP or AD integration would solve the issue. And would make
API-umbrella usable for closed networks.

PS: I did notice a few js libs being remotely referenced, this would also
break in my case.

Thanks for getting back to me.

Tor Inge Skaar

**Comment by GUI** [comment]
Good point on the external JS libraries. Yeah, if you're looking for a completely offline solution, I think our main external dependency in the admin is [Google Charts](https://developers.google.com/chart/) for the analytics graphs. I believe all the other pieces of the admin should work without an internet connection, though (but I haven't looked super closely).

Replacing Google Charts for the analytics graphs is doable, but would require some additional work. One option that's been on my radar if this is something we tackle one day is [ECharts](http://ecomfe.github.io/echarts/index-en.html). There are a lot of other graphing options in this space, but ECharts seems like it might be nice, since it's a rather complete charting library that would cover most of our needs, and the licensing is friendly to inclusion (versus something like HighCharts, which I like and use on other projects, but it's non-commercial stipulation might make it less useful for others).

**Comment by GUI** [comment]
This is an old issue, but as a heads up, the v0.14.0 release of API Umbrella should now be able to operate offline (there's an option for local admin accounts, and there's no external javascript references anymore).
