### ISSUE TITLE
routing error

### ISSUE THREAD

**Issue by dmolina-ot** [NREL/api-umbrella#128]
I am doing performance testing and about 100 request per second, API Umbrella started to reponse http error with code 429.

Checking router-error.log, I can see:
2015/03/31 11:35:52 [error] 592#0: *10881 limiting requests, excess: 200.300 by zone "api_umbrella_req_addr_zone", client: xxx.xxx.xxx.xxx, server: localhost, request: "GET /categories/headercachecontrol HTTP/1.1", host: "my.api.com"

What is the problem?

**Comment by GUI** [comment]
Are you testing with an API or specific API key that has it's rate limits set to unlimited? If not, you should do that so the api-umbrella-gatekeeper doesn't perform rate limiting.

If you're already doing that, then I suspect you're hitting some lower-level global rate limits we also apply by default at the nginx layer (mainly to prevent abuse). Unfortunately, this setup is slightly confusing, since it means an api key that's set to unlimited requests still might encounter these global rate limits. We typically set these global limits much higher than legitimate traffic we would expect, and these global limits just help prevent true abuse. However, you you may need to tune them differently for your own traffic and definitely bump into them when performing benchmarking.

The can view the [default values here](https://github.com/NREL/api-umbrella-router/blob/0c971ef241d9828995979dcea41bcbf762361ef2/config/default.yml#L81-L86). `router.global_rate_limits.ip_rate` controls the requests per second allowed per IP address and `router.global_rate_limits.ip_connections` controls the maximum number of concurrent connections an IP may hold open. So for benchmarking, you might just set them absurdly high so they don't interfere by making a change like this to your `/etc/api-umbrella/api-umbrella.yml` config file:

```yml
router:
  global_rate_limits:
    ip_rate: "1000000r/s"
    ip_connections: 100000
```

But for production use, you may want to set those to more sane values if you want this type of lower-level global rate limiting (but if you don't, then just leave them high).

Overall, these global rate limits are something I'd like to get rid of, though. They help with certain types of malicious abuse (since they stop the request at the nginx layer before hitting the gatekeeper layer which is slightly more resource intensive), but they're confusing, since they're layered on top of the rate limits defined in API Umbrella. I'm hoping we can revisit these and get rid of them as part of https://github.com/NREL/api-umbrella/issues/86

**Comment by dmolina-ot** [comment]
Thank you. 
It was suspected that the limit value was 100 so it should be something configured.  

ip_connections must be less than 65536. 

I get in router-nginx.log:
nginx: [emerg] connection limit must be less 65536 in /opt/api-umbrella/etc/nginx/./frontend_defaults.conf:2
