### ISSUE TITLE
What is Admin Console > Users > Add API Scope?

### ISSUE THREAD

**Issue by dmolina-ot** [NREL/api-umbrella#130]
What is Admin Console > Users > Add API Scope?

**Comment by GUI** [comment]
@dmolina-ot: I'm very sorry for the extremely belated response. We should add more inline help to describe this functionality since it's not particularly obvious, but essentially API Scopes are combined with the Admin Groups to create a granular permission system within the API Umbrella admin. This might be useful if you have multiple organizations or departments that should only have access to certain parts of the API Umbrella admin.

It starts by setting up an API Scope, which defines a hostname and a path prefix. This sets up the API backends and analytics an admin is allowed to view (for example, an admin is authorized to interact with `example.com/foo/*` apis, but not `example.com/bar/*` apis). Next, you setup a group, which defines the specific permissions admins can perform within API scopes (for example, you may want some admins to only be able to view analytics, while others should be able to also setup API backends).

As a quick example, let's say I setup an API Scope with a host of `example.com` and a path prefix of `/foo`. I then create a group that uses that scope and grants the `Analytics` and `API Backend Configuration - View & Manage` permissions. I then assign that group to a specific admin account. Now any admin that belongs to that group can login and view analytics, but only for requests beginning with `example.com/foo/*`. They would not be able to view analytics for `example.com/bar/`. Similarly, because they were granted the API Backend permission, that user could edit or create new API backends, but only as long as the API backend they're interacting with starts with `example.com/foo/*` for it's public URL. However, while this specific admin group could add and edit API backends, they couldn't actually publish the backend changes and make them live, since they were not granted the `API Backend Configuration - Publish` permission.

Does all that make sense?

**Comment by brylie** [comment]
This would be a useful documentation page.

**Comment by GUI** [comment]
Closing since this documentation got added in https://github.com/NREL/api-umbrella/pull/136 and is available at: https://api-umbrella.readthedocs.org/en/latest/admin/admin-accounts/permissions.html
