### ISSUE TITLE
LDAP Authentication?

### ISSUE THREAD

**Issue by jyjohnson** [NREL/api-umbrella#131]
Hi - I see OmniAuth has some support for LDAP. What kind of work would be needed to get API Umbrella to support LDAP?

Thanks.

**Comment by GUI** [comment]
@jyjohnson Sorry for the delay! This should be easy for us to support. It's mostly a matter of us bundling the omniauth-ldap plugin, and then you can configure it for use.

I've gone ahead and [added omniauth-ldap](https://github.com/NREL/api-umbrella-web/commit/20371c868389ed33c1b408e9f2a6e84cae04ed3c) to our project, so that will be packaged in our next release (v0.9, which I'm hoping we get released sometime in the next couple weeks). However, if you're keen to play with this now, you can [deploy api-umbrella-web from master](http://apiumbrella.io/docs/deployment/).

To configure it for use, I've gone ahead and added docs for how to enable it and then pass the configuration options to it on the [Authentication Strategies](https://github.com/NREL/api-umbrella/wiki/Authentication-Strategies) page.

But give a shout if you have any other questions.
