### ISSUE TITLE
Document API Umbrella developer integraiton options

### ISSUE THREAD

**Issue by brylie** [NREL/api-umbrella#133]
There may be multiple options for developing custom code based on, and/or extending, API Umbrella functionality. Document available options including risks and benefits for each.

Deliverable
----------------
* [ ] [Wiki page](https://github.com/NREL/api-umbrella/wiki/Integration-Options) describing integration options

User Stories
-----------------
As a developer
I need to know options available to integrate my code with API Umbrella
so that I can decide on which strategy to take when extending API Umbrella functionality

As a project manager
I need to understand how to integrate custom code with API Umbrella
so that I can create a development plan and specification

**Comment by brylie** [comment]
@GUI will you validate my assertions in the [Integration options] wiki document, and possibly expand a bit on the possibilities?

**Comment by GUI** [comment]
This all looks good, except I made a couple [small adjustments](https://github.com/NREL/api-umbrella/wiki/Integration-Options/_compare/0d3c5d68647cfbeba1d02f302353c8060273daf0...b9724de9dae89d3cf4abd9bec80d7eeb3c7db393), since our configuration is stored in Mongo, not Redis. Assuming I understand what config you're talking about, most everything like API backend configuration and API user accounts gets stored in Mongo. Redis is only used for tracking rate limits.

In terms of overall integration, though, if you're looking to build a dashboard on top of API Umbrella, then I think you'll predominantly be interacting with APIs exposed by the api-umbrella-web component. The APIs the web component provides should facilitate reading or writing the various bits of config out of the entire API Umbrella system. So while the APIs live in the web component, they typically have an effect on the other components, since all the components read and write out of Mongo for shared configuration. So for example, the web component provides APIs to read or write API users or API backends, but both of those end up impacting the router and gatekeeper components automatically, since those other components read config immediately from the Mongo database when changes are detected.

Does all that make sense and help with your integration planning? If not, definitely feel free to give me a holler, and I'd be glad to talk about things in more detail.

**Comment by brylie** [comment]
This looks good. I am interested in learning more about how to access the Gatekeeper directly, if possible. We also need to access analytics data, and are not sure how to do that.
