### ISSUE TITLE
How does "host rewrite to" work?

### ISSUE THREAD

**Issue by elnzv** [NREL/api-umbrella#148]
Not everything clear with these fields on configuration API Backend.
![screencapture-apinf-com-admin-1433333466861](https://cloud.githubusercontent.com/assets/7489044/7959569/03e7265a-0a03-11e5-947a-6be407fb15f1.png)

We have already defined backend host before in the form, so it seems like duplication.
Could you please help with explanation, and also we can document it.

**Comment by GUI** [comment]
Sorry for the delay in response.

Yeah, unfortunately this piece is a bit confusing, and we need to better explain this, but these various host fields actually do provide slightly different things:

- In the "Backend" section, what you are providing are server names and connection information (port and protocol) for where you're API lives. The server name can be a domain name or an IP address. If you're using API Umbrella to load balance between multiple servers then each one of these could be added there.
- In the "Host" section, you're defining how to handle and treat the [`Host` HTTP header](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23) on the request. A vast majority of the time, the backend host will match the server name added above (which is why we recently changed the UI to make these values default to be the same). However, if you're load balancing between multiple servers or doing other things with virtual host names, then the values may differ.

As a quick example of how this might work in a load balanced setup, let's say you have two servers, `my-api1.example.com`, and `my-api2.example.com`. You would add both of those as individual servers under the "Backend" section. But if each of those API backends were listening for the domain name `my-api.example.com` as a named virtual host, then you would set that as the "Backend Host" value in the "Host" section.

There are a couple of other use-cases for this distinction (eg, connecting to a backend server by IP address, but still using a backend host for named virtual hosts), but none of this is probably too common. So while I think we could definitely improve this UI, does that distinction at least make sense? "Servers" is basically the connection information for the underlying server(s), while "Host" defines how to parse and rewrite the `Host` HTTP header.

Let me know if you have any other questions or suggestions.
