### ISSUE TITLE
Full CRUD Admin API

### ISSUE THREAD

**Issue by brylie** [NREL/api-umbrella#152]
Add full CRUD (Create, Read, Update, Delete) methods to Admin API for all API Umbrella data objects.

## User Story
```
As an application developer
I would like to have full CRUD methods for all API Umbrella data objects
so that I can fully integrate my application with the API Umbrella platform
```

### API Users
* [x] [Create](http://apiumbrella.io/docs/admin-api/#users-/-api-keys-user-collection-post)
* [x] [Read](http://apiumbrella.io/docs/admin-api/#users-/-api-keys-user-get)
* [x] [Update](http://apiumbrella.io/docs/admin-api/#users-/-api-keys-user-put)
* [x] [Delete](https://github.com/NREL/api-umbrella/issues/149)

### API Backends
* [x] [Create](http://apiumbrella.io/docs/admin-api/#api-backends-api-backend-collection-post)
* [x] [Read](http://apiumbrella.io/docs/admin-api/#api-backends-api-backend-get)
* [x] [Update](http://apiumbrella.io/docs/admin-api/#api-backends-api-backend-put)
* [x] [Delete](https://github.com/NREL/api-umbrella/issues/150)

### Admin Users
* [x] [Create](http://apiumbrella.io/docs/admin-api/#admin-accounts-admin-collection-post)
* [x] [Read](http://apiumbrella.io/docs/admin-api/#admin-accounts-admin-get)
* [x] [Update](http://apiumbrella.io/docs/admin-api/#admin-accounts-admin-put)
* [ ] [Delete](https://github.com/NREL/api-umbrella/issues/151)

### API Scopes
* [x] Create
* [x] Read
* [x] Update
* [x] Delete

### Admin Groups
* [x] Create
* [x] Read
* [x] Update
* [x] Delete

**Comment by GUI** [comment]
Thanks for pulling this together as a cohesive list! Nothing quite like checkboxes to make it clear what's missing. :)

We do already have CRU[D] APIs (well, lacking the deletes like seemingly most everything else) for API Scopes at [`/api-umbrella/v1/api_scopes`](https://github.com/NREL/api-umbrella-web/blob/master/app/controllers/api/v1/api_scopes_controller.rb) and Admin Groups at [`/api-umbrella/v1/admin_groups`](https://github.com/NREL/api-umbrella-web/blob/master/app/controllers/api/v1/admin_groups_controller.rb). But I'll try to get the DELETEs implemented everywhere soon and finally, finally get all the API documentation updated on all this.

**Comment by brylie** [comment]
@GUI thanks for the quick response. We have [another issue](https://github.com/NREL/api-umbrella/issues/129#issuecomment-109894668) open regarding the documentation, with the [idea to produce a Swagger or RAML description of the Admin API](https://github.com/NREL/api-umbrella/issues/129#issuecomment-109894668). What do you think of the Swagger/RAML description file idea?

**Comment by GUI** [comment]
@brylie: Sorry again for the delays. I believe I've added all the missing CRUD endpoints in master (https://github.com/NREL/api-umbrella-web/commit/fafa1a85e4f83e8ce7ef81f27135232d396fc507) with the exception of a DELETE action for users. However, users can be disabled, which should effectively be the same.

If you do want to delete users, let me know, since that would be helpful to know. We can certainly add delete capabilities, there's just a bit more to [figure out](https://github.com/NREL/api-umbrella/issues/134#issuecomment-101907183) (mainly soft deletes vs hard deletes, but also analytics implications).

And I definitely like the idea of a RAML or Swagger specification for all these API endpoints. I was hoping to get that those docs fully written for all of these endpoints as part of this update, but unfortunately I haven't gotten that done and I'll be without much internet access for the next couple weeks. So it will be a few weeks before I can circle back to this, but I do really want to get the docs updated so all of this is more clearly documented. Do you have any preferences on RAML vs Swagger, or does either one suit you?

**Comment by brylie** [comment]
@GUI can we please discuss the Admin API documentation in the [related issue](https://github.com/NREL/api-umbrella/issues/129)?

**Comment by GUI** [comment]
I'm going to go ahead and close this since the missing DELETE endpoints have been added and the documentation has been updated.

**Comment by sandeepkottagundu** [comment]
I creating user using postman tool it will created user successfully but it will calll in my front end application it will give 403 error(Response for preflight has invalid HTTP status code  403) please give response as soon as possible

**Comment by sandeepkottagundu** [comment]
but it will generated api key on apiumbrella/admin -> users ->API Users it will not send back to the apikey on email it will show as above comment 403 error
