### ISSUE TITLE
Api umbrella start error

### ISSUE THREAD

**Issue by ineot** [NREL/api-umbrella#170]
api umbrella start error
api umbrella version 0.8

>supervi~.log

log-processor (exit status 8; not expected)
![image](https://cloud.githubusercontent.com/assets/10915011/9961917/15d5df1e-5e5e-11e5-979c-ae0a46ef3098.png)

>log-processor.log
![image](https://cloud.githubusercontent.com/assets/10915011/9961969/4dfa38a4-5e5e-11e5-9ef3-6e92b773ab5d.png)

**Comment by GUI** [comment]
Interesting, thanks for the report. One quick question: is this on a new installation of API Umbrella or an existing installation?

Since the user agent parsing stuff is erroring, I suspect this is due to the fact that the user-agent-string.info site we were using for user agent data went away last year. API Umbrella should be using a cached version of the user agent data, but perhaps something wiped that cache. Everything has still been working on existing and new installations of API Umbrella for me since the user-agent-string.info site changed last year, but this has been in the back of my mind as a potentially problematic area. I'll try to take a look soon to see what might lead to this happening.

**Comment by ineot** [comment]
Thanks. for reply.

answer : New installation of API Umbrella . May be at 2015-07 .. version 0.8

Log in Elastic search did not record any more.
So, an error occurred while restarting the API Umbrella.

How do to fix this?

---------
P.S The same error occurred on the same day two servers
one server is reinstall .. it server success start.
However, in September, data on the Elastic search was deleted

Please let me know if you need to troubleshoot further.
-------
current...

not reinstall server 

apiumbrella.yml

services
 - gene~
 #log .. expcept log service
 - router
 -

**Comment by ineot** [comment]
current.. i know.
and i try to replay symptoms...

- cleaner.js file..

    module.exports.userAgent = function(log, callback) {
    ~ }

- console.log(log);
  request_user_agent : 1 ....  << this... not "Mozilla....~~~"

 not match error....;;

**Comment by GUI** [comment]
Apologies for never getting back to you. I'm still not sure what caused this, but we have new v0.9 packages out which should hopefully eliminate the possibility of this error: https://apiumbrella.io/install/ Let us know if you're still running into any problems.
