### ISSUE TITLE
VM needs new dependencies

### ISSUE THREAD

**Issue by cmc333333** [NREL/api-umbrella#182]
Without these packages, the `make` command fails

`xz`

`pcre-devel`
complaint about PCRE not being present

`tcl-devel`
checking for Tcl configuration... configure: error: Can't find Tcl configuration, install the TCL dev package

`libxml2-devel`
configure: error: An XML parser (expat or libxml2) is required.

**Comment by GUI** [comment]
Also need `libyaml-devel`.

@cmc333333: If you pull down the latest from master and install that `libyaml-devel` dependency, I think it should hopefully fix the issues you were seeing earlier. Basically, the build error we were seeing was a bit of a red herring due to several odd issue, but it should be fixed by https://github.com/NREL/api-umbrella/commit/76807831d8685493c87f200f8dab920ad6e2973f

**Comment by GUI** [comment]
`libuuid-devel` too.

**Comment by cmc333333** [comment]
For future search, the error message around `libuuid-devel` was

```
0151015T205502.118841: 2015/10/15 20:55:01 [error] 8197#0: init_worker_by_lua_file error: ...vagrant/api-umbrella/vendor/share/lua/5.1/resty/uuid.lua:29: libuuid.so: cannot open shared object file: No such file or directory
```

**Comment by cmc333333** [comment]
Ran through this from a fresh vagrant image. Dependencies as a checkbox list
* [ ] xz
* [ ] libyaml-devel
* [ ] tcl-devel
* [ ] libxml2-devel

**Comment by GUI** [comment]
All of these should be part of the vagrant setup now.
