### ISSUE TITLE
Admin API Model Schema has "settings" Object inside "sub-settings" Array

### ISSUE THREAD

**Issue by jykae** [NREL/api-umbrella#185]
Trying to get add "default_response_headers_string" to API Post call, when I found out that Umbrella Model Schema expects really weird structure for "sub_settings":

<pre>
"sub_settings": [
      {
        "id": "string",
        "http_method": "any",
        "regex": "string",
        "settings": {
          "id": "string",
          "append_query_string": "string",
          "headers": [
            {
              "id": "string",
              "key": "string",
              "value": "string"
            }
          ],
          "headers_string": "string",
          "default_response_headers": [
            {
              "id": "string",
              "key": "string",
              "value": "string"
            }
          ],
          "default_response_headers_string": "string",
          "override_response_headers": [
            {
              "id": "string",
              "key": "string",
              "value": "string"
            }
          ],
          "override_response_headers_string": "string",
          "http_basic_auth": "string",
          "require_https": "required_return_error",
          "require_https_transition_start_at": "2015-10-29T08:44:30.697Z",
          "disable_api_key": true,
          "api_key_verification_level": "none",
          "api_key_verification_transition_start_at": "2015-10-29T08:44:30.697Z",
          "required_roles": [
            "string"
          ],
          "required_roles_override": true,
          "allowed_ips": [
            "string"
          ],
          "allowed_referers": [
            "string"
          ],
          "rate_limit_mode": "unlimited",
          "rate_limits": [
            {
              "id": "string",
              "duration": 0,
              "accuracy": 0,
              "limit_by": "ip",
              "distributed": true,
              "response_headers": true
            }
          ],
          "anonymous_rate_limit_behavior": "ip_fallback",
          "authenticated_rate_limit_behavior": "all",
          "pass_api_key_header": true,
          "pass_api_key_query_param": true,
          "error_templates": {},
          "error_data": {},
          "error_data_yaml_strings": {}
        }
      }
    ]
</pre>
To examine, open http://apiumbrella.io/docs/admin-api/#!/api/post_api_umbrella_v1_apis AND click on "Model Schema" to set as parameter value. I copy&pasted the structure in code editor to better view the structure.

Why there is "settings" Object again inside "sub_settings"? What is the purpose of having "sub-settings"? Are you planning to improve this?

**Comment by GUI** [comment]
This is actually by design and is related to how settings get inherited or overridden. The basic idea is that the `"settings"` object always defines the same configuration options that can be set at any level of the API matching process.

It might help to think of the `"settings"` object as a standalone schema that is reused in multiple places. Here's the model that defines the schema for that settings object: https://github.com/NREL/api-umbrella/blob/master/src/api-umbrella/web-app/app/models/api/settings.rb

But this settings object can be set in a few different places, from globally to more specific:

- `/etc/api-umbrella/api-umbrella.yml`: The [`"apiSettings"`](https://github.com/NREL/api-umbrella/blob/9bc593600fb06e1699ed6af4dbebbc3a460f1481/config/default.yml#L161-L255) object adheres to this settings schema and defines default settings that will apply across all APIs. By default this is pulled from the internal `default.yml`, but you can also supply overrides in your own `/etc/api-umbrella/api-umbrella.yml`.
  - API Backends: Within the [`Api`](https://github.com/NREL/api-umbrella/blob/9bc593600fb06e1699ed6af4dbebbc3a460f1481/src/api-umbrella/web-app/app/models/api.rb#L27) structure, a `"settings"` object can be defined which defines default settings for when this specific API backend is being routed to. The settings defined at this level be merged on top of the global `"apiSettings"` from the default YAML config.
    - Sub-Settings: Inside of a specific API Backend, you can define Sub-Setting matching rules. This would allow for you to apply different settings to specific types of URLs within the context of an API Backend (so, for example, maybe you want different settings when `POST` requests are made). The Sub-Setting schema itself is just concerned with what should trigger matching that Sub-Setting, but then within the Sub-Setting, the same `"settings"` object is [embedded](https://github.com/NREL/api-umbrella/blob/9bc593600fb06e1699ed6af4dbebbc3a460f1481/src/api-umbrella/web-app/app/models/api/sub_settings.rb#L11) (similar to how it's embedded within the API Backend schema. This allows for us to easily merge just the settings on top of the other settings that might be inherited from the API Backend or the global scope.

Does that make sense? Basically it's so we have a consistent "Settings" object that we can easily merge on top of each other at the various levels. The "Sub-Settings" term might be a confusing choice in names, since it embeds the separate Settings schema object inside of it, but hopefully this explanation will at least help a bit. But any feedback is always welcome.

**Comment by jykae** [comment]
@brylie Check out. And thank you @GUI This obviously helps our work with the Admin API.
