### ISSUE TITLE
GPG signing of binary packages

### ISSUE THREAD

**Issue by GUI** [NREL/api-umbrella#197]
With v0.9 now that we're publishing to proper yum and apt repositories, it would be good to figure out how to properly sign our binary packages so that they don't result in warnings when installing

**Comment by brylie** [comment]
Maybe useful: https://wiki.debian.org/SecureApt

**Comment by brokenjacobs** [comment]
We use spacewalk for distributing packages to RHEL/Centos/OEL systems. Having gpg signed packages would be especially useful, I can't currently push packages in our setup because the rpm's aren't signed. I can re-sign them myself, but it makes the workflow difficult.

Also, I would highly recommend changing the yum repositories to point to the TLS enabled links for bintray. They work already, the files just use HTTP currently.

Is this something I could help with? I'm don't think the issue the actual signing of the packages, its just control over the signing key for publishing releases.

**Comment by GUI** [comment]
Well, this is very belated, but I believe this should be sorted out in the v0.15.1 release, but let us know if not. https://apiumbrella.io/install/
