### ISSUE TITLE
Use semantic versioning for API Umbrella releases?

### ISSUE THREAD

**Issue by brylie** [NREL/api-umbrella#204]
The 0.9 and 0.10 versions were recently released. What versioning convention is being used for API Umbrella releases? What are your thoughts about using the [Semantic Versioning convention](http://semver.org/) for release versioning, if it is not already in use?

**Comment by GUI** [comment]
Yes, we use semantic versioning (which is why despite 0.10 being pretty small, we bumped the minor version, since there were a couple of small new things).

I added some new documentation on our [release process](https://api-umbrella.readthedocs.org/en/latest/developer/release-process.html), where I clarified anyone releasing packages should use semantic versioning, but let us know if you think this should be also documented anywhere else.
