### ISSUE TITLE
Can't Access Homepage after Installation

### ISSUE THREAD

**Issue by leetschau** [NREL/api-umbrella#221]
I installed API Umbrella server on Ubuntu 14.04 server according to [Getting Started](https://api-umbrella.readthedocs.org/en/latest/getting-started.html) guide.
After I modified /etc/api-umbrella/api-umbrella.yml and started api-umbrella server, I can't access it's homepage in the browser.

I've checked the firewall of the server. Port 80 and 443 are all open for incoming request.

When access with `curl umbrella.my.website`, where "umbrella.my.website" is the server running api-umbrella service, I got the following result:

    {
      "error": {
        "code": "NOT_FOUND",
        "message": "The requested URL was not found on this server."
      }
    }

How can I get the homepage like the image below

> Browse to your server’s hostname. You should land on the default homepage:

in the document?

Thanks.

**Comment by GUI** [comment]
@leetschau: Sorry for the delay in responding. This error would seem to indicate that it's trying to route the homepage URL (`http://umbrella.my.website/`) as an API, rather than to the default website content. By default, the website should be the fallback for any unknown URL, so I'm not entirely sure what's triggering this, but a few questions:

- Have you published any API Backends within the admin tool yet? If so, do any of them have a frontend URL prefix of just `/`?
- Have you published any Website Backends within the admin tool?
- In your `/etc/api-umbrella/api-umbrella.yml` config file, have you modified any of the following configuration settings: `router.web_app_host`, `internal_website_backends.frontend_host`, or `hosts`?

**Comment by GUI** [comment]
Going to go ahead and close this issue, but please reach out if you're still having any issues.
