### ISSUE TITLE
Publish a new Ubuntu package

### ISSUE THREAD

**Issue by ThibautGery** [NREL/api-umbrella#254]
I would like to deploy the current version of umbrella (`master`) for `ubuntu 14.04`. I tried to run `./build/package/publish` but it didn't worked. Is there some documentation about this ?
If it's complicated, I will [compile from source](http://api-umbrella.readthedocs.io/en/latest/developer/compiling-from-source.html)

**Comment by GUI** [comment]
There's some documentation on building the binary packages here: https://api-umbrella.readthedocs.io/en/latest/developer/packaging.html

The `./build/package/publish` script is only intended for publishing official packages for release and distribution after they're built. In other words, only API Umbrella maintainers will have this access to perform that action. Sorry if that's not clear in the documentation, we'll try to update that to be more clear.

So if you'd like to build a .deb package, it's the previous `make -C build/package -j4 docker_all` step that would do that. You'll end up with a local `.deb` file that you can install manually by copying the file to your server (but this won't be available in our default apt-get repo).

A couple of additional notes on building the packages:

- The default command above builds packages for all our supported Linux distros (6 packages for different versions of CentOS, Ubuntu, and Debian). If you're just interested in building an Ubuntu 14.04 packages, you can do that a lot more quickly by just building that one package: `make -C build/package docker_ubuntu1404`
- Our packaging process builds the package, and then runs a series of tests against the new package. These tests ensure the package can be installed and API Umbrella runs in a brand new environment. We also do various tests to ensure you can upgrade between API Umbrella package versions (eg, that I can upgrade from v0.10 to v0.11 without issue). I believe there's a small issue in our current packaging process on `master` which will lead to some test failures when trying to perform these package upgrade tests. However, I believe the packages should basically work, there's just some subtle upgrade issues if you're upgrading from a previous API Umbrella version.

Does that help explain things? Let us know if you have any other questions.

But thanks for bringing this up, since I think we have reached a pretty good point to package up everything in master for an official v0.12 release (after we fix the small package upgrade issue). I can look to get v0.12 packages built, tested, and released hopefully sometime within the next week, if that would help.

**Comment by ThibautGery** [comment]
It didn't run correctly:
```sh
$ make -C build/package -j4 docker_ubuntu1404
make: Entering directory `/home/tge/workspace/sgmap/api-umbrella/build/package'
DIST=ubuntu-14.04 make docker
make[1]: Entering directory `/home/tge/workspace/sgmap/api-umbrella/build/package'
/home/tge/workspace/sgmap/api-umbrella/build/package/docker_run > /home/tge/workspace/sgmap/api-umbrella/build/work/package/log/ubuntu-14.04.log 2>&1
make[1]: *** [docker] Error 100
make[1]: Leaving directory `/home/tge/workspace/sgmap/api-umbrella/build/package'
make: *** [docker_ubuntu1404] Error 2
make: Leaving directory `/home/tge/workspace/sgmap/api-umbrella/build/package'
```

Logs:
```sh
$ cat /home/tge/workspace/sgmap/api-umbrella/build/work/package/log/ubuntu-14.04.log
+++++ dirname /home/tge/workspace/sgmap/api-umbrella/build/package/docker_run
++++ cd /home/tge/workspace/sgmap/api-umbrella/build/package
++++ pwd
+++ dirname /home/tge/workspace/sgmap/api-umbrella/build/package
++ dirname /home/tge/workspace/sgmap/api-umbrella/build
+ source_dir=/home/tge/workspace/sgmap/api-umbrella
+ docker_image=ubuntu:14.04
+ container_name=api-umbrella-package-ubuntu-14.04
+ container_name=api-umbrella-package-ubuntu-14.04
+ docker pull ubuntu:14.04
14.04: Pulling from library/ubuntu
Digest: sha256:d67ef8e385f1c8b13d8c3e7622dc31b51d07e5623c1d034ebe2acb14a11fb30d
Status: Image is up to date for ubuntu:14.04
++ docker ps -a -q --filter=name=api-umbrella-package-ubuntu-14.04
+ existing=
+ '[' '' '!=' '' ']'
+ docker run --name=api-umbrella-package-ubuntu-14.04 --volume=/home/tge/workspace/sgmap/api-umbrella:/api-umbrella --env=DIST=ubuntu-14.04 --rm ubuntu:14.04 /bin/bash -c /api-umbrella/build/package/docker_script
+++++ dirname /api-umbrella/build/package/docker_script
++++ cd /api-umbrella/build/package
++++ pwd
+++ dirname /api-umbrella/build/package
++ dirname /api-umbrella/build
+ source_dir=/api-umbrella
+ /api-umbrella/build/scripts/install_build_dependencies
+++++ dirname /api-umbrella/build/scripts/install_build_dependencies
++++ cd /api-umbrella/build/scripts
++++ pwd
+++ dirname /api-umbrella/build/scripts
++ dirname /api-umbrella/build
+ source_dir=/api-umbrella
+ source /api-umbrella/build/package_dependencies.sh
++ '[' -f /etc/redhat-release ']'
++ '[' -f /etc/debian_version ']'
++ core_package_dependencies=(bash libc6 libncurses5 libpcre3 libuuid1 libyaml-0-2 openssl zlib1g libxml2 tcl openjdk-7-jre-headless sysvinit-utils lsb-base procps)
++ hadoop_analytics_package_dependencies=(openjdk-7-jre-headless)
++ core_build_dependencies=(autoconf automake bzip2 cmake curl g++ gcc git libcurl4-openssl-dev libffi-dev libncurses5-dev libpcre3-dev libssl-dev libtool libxml2-dev libyaml-dev lsb-release make openssl patch rsync tar tcl-dev unzip uuid-dev xz-utils)
++ hadoop_analytics_build_dependencies=(openjdk-7-jdk-headless)
++ lsb_release --codename --short
++ grep wheezy
++ core_package_dependencies+=("libffi6")
++ all_dependencies=("${core_package_dependencies[@]}" "${hadoop_analytics_package_dependencies[@]}" "${core_build_dependencies[@]}" "${hadoop_analytics_build_dependencies[@]}")
+ '[' -f /etc/redhat-release ']'
+ '[' -f /etc/debian_version ']'
+ apt-get update
Ign http://archive.ubuntu.com trusty InRelease
Get:1 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]
Get:2 http://archive.ubuntu.com trusty-security InRelease [65.9 kB]
Get:3 http://archive.ubuntu.com trusty Release.gpg [933 B]
Get:4 http://archive.ubuntu.com trusty Release [58.5 kB]
Get:5 http://archive.ubuntu.com trusty-updates/main Sources [348 kB]
Get:6 http://archive.ubuntu.com trusty-updates/restricted Sources [5217 B]
Get:7 http://archive.ubuntu.com trusty-updates/universe Sources [197 kB]
Get:8 http://archive.ubuntu.com trusty-updates/main amd64 Packages [979 kB]
Get:9 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [23.5 kB]
Get:10 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [467 kB]
Get:11 http://archive.ubuntu.com trusty-security/main Sources [148 kB]
Get:12 http://archive.ubuntu.com trusty-security/restricted Sources [3920 B]
Get:13 http://archive.ubuntu.com trusty-security/universe Sources [43.2 kB]
Get:14 http://archive.ubuntu.com trusty-security/main amd64 Packages [618 kB]
Get:15 http://archive.ubuntu.com trusty-security/restricted amd64 Packages [20.2 kB]
Get:16 http://archive.ubuntu.com trusty-security/universe amd64 Packages [169 kB]
Get:17 http://archive.ubuntu.com trusty/main Sources [1335 kB]
Get:18 http://archive.ubuntu.com trusty/restricted Sources [5335 B]
Get:19 http://archive.ubuntu.com trusty/universe Sources [7926 kB]
Get:20 http://archive.ubuntu.com trusty/main amd64 Packages [1743 kB]
Get:21 http://archive.ubuntu.com trusty/restricted amd64 Packages [16.0 kB]
Get:22 http://archive.ubuntu.com trusty/universe amd64 Packages [7589 kB]
Fetched 21.8 MB in 3s (5849 kB/s)
Reading package lists...
+ apt-get -y install bash libc6 libncurses5 libpcre3 libuuid1 libyaml-0-2 openssl zlib1g libxml2 tcl openjdk-7-jre-headless sysvinit-utils lsb-base procps libffi6 openjdk-7-jre-headless autoconf automake bzip2 cmake curl g++ gcc git libcurl4-openssl-dev libffi-dev libncurses5-dev libpcre3-dev libssl-dev libtool libxml2-dev libyaml-dev lsb-release make openssl patch rsync tar tcl-dev unzip uuid-dev xz-utils openjdk-7-jdk-headless
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package openjdk-7-jdk-headless
```

To me, the build system is a blackbox. It is really complex and hard to evolve and debug.

**Comment by GUI** [comment]
@ThibautGery: Sorry about that! This should actually be fixed in master now if you pull down the latest.

I had discovered the same bug a couple days ago when I was preparing things for the v0.12 release (which we should hopefully have published in the next couple days). We had a package dependency error for Ubuntu systems defined in [`build/package_dependencies.sh`](https://github.com/NREL/api-umbrella/blob/master/build/package_dependencies.sh). There was a dependency defined for a non-existent `openjdk-7-jdk-headless` package, so that's what caused this Ubuntu build process to die with the `Unable to locate package openjdk-7-jdk-headless` error. This was a typo/mistake, since the actual package we needed to depend on for Ubuntu was `openjdk-7-jdk` (without the `-headless`).

This was fixed as part of https://github.com/NREL/api-umbrella/commit/09f8f3cf72e5a6031da87d007a8d8e5b5a466633, although I forgot to mention it in the commit notes (and really, I probably should have a made a separate commit for that fix--whoops on both counts!).

I am going to look into ways we can automate the testing of our build/packaging process on a more regular basis, so we can catch these type of distro-specific issues more quickly. Since we don't actively use Ubuntu ourselves, we tend to only find these bugs when we're building all the distro packages for a release, or when someone else tries and runs into an error (which is no fun).

And yes, unfortunately the build process is somewhat complex. We can try to provide a general overview of the process in our docs, or is there anything in particular you have questions on or would like to see further documentation on?

**Comment by ThibautGery** [comment]
> I was preparing things for the v0.12 release (which we should hopefully have published in the next couple days)
Yay \o/
I will try to summarise my experience as a new developer in a mail with the thing I had to reverse engineer (Hopefully I will write a PR of documentation
Thank you for the fix.

**Comment by GUI** [comment]
The v0.12.0 packages have been released: https://groups.google.com/forum/#!topic/api-umbrella/x5GfWdnho1M

And yeah, we'd welcome any feedback on hurdles you ran into or any areas we could improve the documentation. Thanks!
