### ISSUE TITLE
Set default cache rule

### ISSUE THREAD

**Issue by rogeriollacerda** [NREL/api-umbrella#269]
Hi,

Is possible set default cache rule for all apis? Something like set cache header if it does't come from API response.

**Comment by GUI** [comment]
Currently, no, this isn't possible. We rely on the API backend responding with the appropriate cache control headers.

However, I think there is a use-case for forcing caching when you may not be in complete control of the API backend and are unable to have it send the appropriate headers directly. Is that the issue you're facing?

I think the best solution would be to have this utilize the existing "Default Response Headers" and "Override Response Headers" options we have for API Backends. Intuitively, I think those should work, but unfortunately they don't currently work for setting cache control headers, since this logic is performed after the caching layer handles the response. In order to fix this, we'd need to shift the order of when these header overrides get applied so they happen before the caching layer.

This is something I'd like to tackle at some point, since we've also had some situations where this would be handy. However, I'm not exactly sure when we might get to it, so we'd also welcome any pull requests.

**Comment by rogeriollacerda** [comment]
@GUI Tks! It's Ok.
