### ISSUE TITLE
Backend API Timeout

### ISSUE THREAD

**Issue by noobfoot** [NREL/api-umbrella#273]
I've installed api-umbrella and added 3 APIs.  All of them forward requests to analytic services which vary in response times depending on the analysis request.  Some analysis could take up to a couple of hours...  My network connections are not the problem.  If I go directly to the analytic services the response times are about the same as if I were to go thru api-umbrella.  Initially I was receiving 504 errors from api-umbrella, so I updated the api-umbrella's proxy_connect_timeout: 

```
nginx:
  proxy_connect_timeout: 300
```

I'll probably have to come up  with a decision on what I consider to be a reasonable max time for a request going thru api-umbrella.  I'd like some feedback on a couple of things:

- What does the api-umbrella team suggest as far as configurations for response times from backend APIs that vary.  Not necessarily only the proxy_connect_timeout value, but also any other configurations that I can adjust.

- Is this the correct configuration setting to adjust when backend APIs take a while to respond?

**Comment by GUI** [comment]
Apologies for the delay in following up. There are 3 primary [timeout settings](https://github.com/NREL/api-umbrella/blob/v0.13.0/config/default.yml#L18-L20), with each one corresponding to the nginx configuration setting of the same name:

- [`nginx.proxy_connect_timeout`](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_connect_timeout)
- [`nginx.proxy_read_timeout`](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout)
- [`nginx.proxy_send_timeout`](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_send_timeout)

Each of these defaults to 60 seconds. In your case, I think you'll probably want to adjust `proxy_read_timeout`, and not `proxy_connect_timeout`. The connection timeout is only relevant for establishing the initial connection to the backend server, which is usually very quick as long as the backend server is up (even if the backend takes a long time to start responding with data). The read timeout is what typically controls the timeout for long-running responses (but as the nginx docs note, this is the timeout between two successive chunks of data, so if your API streams back data in chunks, then the overall response time can exceed this timeout).

I'm not sure I personally have any concrete recommendations for timeouts. Typically most APIs I see are quick and easily fit under the 60 second timeout. On some occasions we've tuned this upward to deal with APIs that might take a few minutes to respond. I don't have much experience with APIs that take hours to respond, but presumably if you tune the timeouts high enough, the network is stable, and the client doesn't drop the connection, then this should work.

Although, for these type of long-running APIs, another approach I have seen is changing the API to be more of a polling/job model. In this case, the client might make an initial request to submit their job and immediately receive an identifier for their job back. They can then poll a different API endpoint to check the status of their job until it is complete. In this case, each of the requests can be quick, so you might not run into timeout issues. While it's a little more work for the client, an approach like this can sometimes be beneficial, since the task can continue to run in the background even if the client gets disconnected. But there's certainly other approaches, and depending on your use-case long running requests might be just fine.

**Comment by noobfoot** [comment]
Thank you for the detailed response :)

I looked into those settings that correlate to NGINX settings and your explanation further expanded my understanding.  I'll try to adjust the `proxy_read_timeout` for my deployment then.

We'll definitely need to consider updating our APIs to the polling/job model you described.

Thank you again for your thoughts!
