### ISSUE TITLE
Question: Removing API Backend through Admin API

### ISSUE THREAD

**Issue by alfredjkwak** [NREL/api-umbrella#280]
How is the Elasticsearch analytics data handled when I remove API backend from Umbrella using Admin API? If I want related data also removed do I need to call also something else?

If I later on add new backend with same Frontend prefix that can be confusing to see old data.

**Comment by GUI** [comment]
We don't ever delete analytics data by default. I guess from our own usage, we view API backends as more of an internal routing detail that shouldn't affect analytics. So even if an API backend gets deleted and replaced, as long as the URLs are the same, we still consider it part of the same logical API from an analytics perspective (since if the URL stayed the same, then API consumers presumably haven't seen any differences in the API, even if the backend routing has changed). Does that approach make sense, or do you use API backends differently?

That being said, if you did want to delete analytics data, it should be possible to do this manually in the Elasticsearch database. However, I'm not sure if Elasticsearch is optimized for bulk deletes, so you might need to be a little careful of the performance implications, depending on how much analytics data is stored in Elasticsearch.

To perform this manually, you could use the [deprecated Delete By Query API](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/docs-delete-by-query.html) in our current version of Elasticsearch (1.7). But as noted, this is a deprecated API that will disappear once we upgrade to Elasticsearch 2. For that version, you'd need the [Delete by Query Plugin](https://www.elastic.co/guide/en/elasticsearch/plugins/current/plugins-delete-by-query.html) (which also talks a bit more about why it was deprecated and some of the performance implications).

**Comment by GUI** [comment]
Closing now, but let us know if you have further questions.
