### ISSUE TITLE
Not able to see numbers in Analytics screen

### ISSUE THREAD

**Issue by anshulbhargava** [NREL/api-umbrella#300]
Hi,
     I jus installed API Umbrella on one of Google Cloud Machines. It works fine and the api proxying works as expected. However, when I navigate to any of the analytics-related screens, I see no metrics. The screen renders properly but the numbers are all zeroes. I guess it has something to do with database interaction, and I tried debugging the possible issues a lot, but without any success. 

Attaching the screenshot for reference. 
<img width="1278" alt="screen shot 2016-11-07 at 5 35 42 pm" src="https://cloud.githubusercontent.com/assets/22934192/20057334/f154731c-a510-11e6-983a-de8862adef66.png">
Can anyone please point out what might the issue be?

**Comment by kalyanmulampaka** [comment]
I have the same issue.
No data in the analytics. apis are working fine.

**Comment by kalyanmulampaka** [comment]
Restarting the docker container fixed the issue. I can now view the analytics.

**Comment by anshulturvo** [comment]
Thanks Kalyan. My installation was, however, not on docker. It was a Ubuntu install. Not sure how to fix in that one.

**Comment by GUI** [comment]
@anshulturvo: Sorry for the trouble and delay. Inside your Ubuntu machine, if you try `sudo /etc/init.d/api-umbrella reload` and then try making some requests, do the analytics then load? If that doesn't work, what about trying `sudo /etc/init.d/api-umbrella restart`?

If this is what I think it is, then there might sometimes be a race condition on the very first startup that resolves itself after a single reload or restart. If reloading or restating  fixes it for you, that would be useful to know. I believe we might have this possible race condition already fixed in master, so if this is the culprit, it should be part of the next release. But if reloading doesn't work, let us know, and we can try to get to the bottom of it.

**Comment by GUI** [comment]
The analytics issues with docker containers, as well as another possible race condition on startup have been fixed in the v0.14.0 release. So I think this should be fixed, but let us know if you're still seeing any issues.
