### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by mafiu** [NREL/api-umbrella#309]
Dear api-umbrella team,

We're using API-Umbrella with our api's without any problem, but a few days ago we launch an API that takes 75 seconds to return data. (Yes, might not be appropriate)

We changed the timeout from nginx to 90 seconds with the configuration `nginx.proxy_read_timeout: 90s` as you said in https://github.com/NREL/api-umbrella/issues/273, but it still not working as expected.

There's also a strange behavior, with 1 request, there are 3 request to our backend (My backend response is in 65 seconds):

X.X.X.X - - [21/Nov/2016:12:59:52 -0300] "GET / HTTP/1.1" 499 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36" aogue88drm7ak9ltgmtg http://4b2a6f8e-72b0-4147-8f21-3db12ebbb8b6:14011 61.235 -

X.X.X.X - - [21/Nov/2016:13:00:23 -0300] "GET /sleep/ HTTP/1.1" 504 578 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36" aogue88drm7ak9ltgmtg https://lab:443 92.002 MISS

X.X.X.X - - [21/Nov/2016:13:00:54 -0300] "GET / HTTP/1.1" 499 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36" aogue88drm7ak9ltgmtg http://4b2a6f8e-72b0-4147-8f21-3db12ebbb8b6:14011 61.973 -

X.X.X.X - - [21/Nov/2016:13:01:56 -0300] "GET / HTTP/1.1" 499 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36" aogue88drm7ak9ltgmtg http://4b2a6f8e-72b0-4147-8f21-3db12ebbb8b6:14011 61.967 -

Have you any idea why it's happening?

**Comment by GUI** [comment]
Thanks for the detailed report. Could you try also adjusting `nginx.proxy_connect_timeout` too? So something like this in your `/etc/api-umbrella/api-umbrella.yml`:

```yml
nginx:
  proxy_connect_timeout: 90
  proxy_read_timeout: 90
```

Based on the fact that you're seeing 3 duplicate requests, I think this might be a way to workaround the problem. If this works, I'd be interested in knowing, since I think we can make this work as intended (so you only have to adjust `nginx.proxy_read_timeout`) in future API Umbrella releases.

For a bit more detail: I don't think nginx's connection timeout technically needs adjusting, but the problem is that we're using that same `nginx.proxy_connect_timeout` setting to calculate some other timeouts in our stack. Specifically, I believe the problem stems from us reusing nginx's connection timeout to set TrafficServer's (the HTTP caching layer) `connect_attempts_timeout` setting. While nginx's "connect" timeout is related to the backend server accepting the TCP connection (which is usually quick, even if the response is slow), it looks like TrafficServer's "connect" timeout setting is actually the timeout for receiving the first byte back in response (which is closer in concept to nginx's read timeout). So I think to resolve this, we may just need to change how we calculate TrafficServer's timeouts.

Related code:
https://github.com/NREL/api-umbrella/blob/v0.13.0/src/api-umbrella/cli/read_config.lua#L315-L338
https://github.com/NREL/api-umbrella/blob/v0.13.0/templates/etc/trafficserver/records.config.mustache#L33-L44

**Comment by mafiu** [comment]
Thanks @GUI for your quick response.

It works setting both variables, now I see 1 backend request a 1 response in logs.

X.X.X.X - - [22/Nov/2016:09:27:14 -0300] "GET / HTTP/1.1" 200 11 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36" aohg02a5osidham4sa60 http://4b2a6f8e-72b0-4147-8f21-3db12ebbb8b6:14011 65.008 -

X.X.X.X - - [22/Nov/2016:09:27:14 -0300] "GET /sleep/ HTTP/1.1" 200 11 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36" aohg02a5osidham4sa60 https://lab:443 65.024 MISS

**Comment by mafiu** [comment]
@GUI, now we're getting some 502 errors, all of them with a response time of ~ 62 seconds, have you any idea why we're getting this error?

**Comment by GUI** [comment]
@mafiu: Hm, I've tried reproducing this, but I can't reproduce the 502 errors. While I can reproduce the original issue you described, once I adjust `proxy_connect_timeout` and `proxy_read_timeout` to `90`, then things appear to be working. Can you share more details from the following log files when this occurs?

- `/var/log/api-umbrella/nginx/access.log`
- `/var/log/api-umbrella/nginx/current`
- `/var/log/api-umbrella/trafficserver/error.log`

I'm hoping one of those might better pinpoint what's going on.

**Comment by mafiu** [comment]
@GUI, I think that this was a backend issue, thanks for your quick response
