### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by parmeshashwath** [NREL/api-umbrella#321]
Hi All,
 I completed the installation procedure and was able to successfully start the api-umbrella . But I am not able to browse to my server name and see the default landing page. Can you please help me on it.
I tried installing Apache httpd and tried to access and was able to see the Apache httpd homepage so the server is accessible. Only with api-umbrella started i don't get any response

**Comment by GUI** [comment]
Are you running API Umbrella on the same server as Apache? By default, API Umbrella will try to listen on ports 80 and 443, so that might be conflicting with Apache if you're running both on the same server.

If that's not the issue, can you describe in more detail what you're seeing when you try to navigate to API Umbrella? Do you get a 404 Not Found page, or something else?

**Comment by parmeshashwath** [comment]
I am not running Apache httpd server when I am running api-umbrella. when I checked it with Apache httpd running ,its home page is accessible. however if I stop it and start API umbrella(it starts successfully) and when I navigate to URL its giving 404 error. Can you please help
