### ISSUE TITLE
Add New Admin Group Error

### ISSUE THREAD

**Issue by ApelSYN** [NREL/api-umbrella#347]
Hello!

When we configured api umbrella admin part, we notice an issue with Users area
Steps to reproduce - _Users>Admin Groups>+ New Admin Group_
While trying to add new admin group form appears and in the console an error occurs:
```
error-messages.js:5 Uncaught TypeError: Cannot read property 'replace' of undefined
    at n.<anonymous> (error-messages.js:5)
    at d.f.get (ember.prod.js:17749)
    at n.<anonymous> (error-messages.js:81)
    at d.f.get (ember.prod.js:17749)
    at n.value (ember.prod.js:14645)
    at n._compute (ember.prod.js:10333)
    at n.value (ember.prod.js:14645)
    at Object.i [as default] (ember.prod.js:10169)
    at Object.a [as getArrayValues] (ember.prod.js:14955)
    at n.compute (ember.prod.js:14025)
```

Api umbrella: v0.14.0 (from yum repository)
OS: CentOS 7.0
Browser: Google Chrome 57.0.2987.98 (64-bit), the same situation for Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
Screenshot: [Screenshot 2017-03-29 17-44-23.png](http://linux.ria.ua/img/api-umbrella/Screenshot%202017-03-29%2017-44-23.png)

Maybe not the ability of one such problem.

**Comment by GUI** [comment]
Apologies for the delay in responding, but thanks for the detailed bug report! This was definitely a bug that cropped up in the 0.14.0 release, our bad for not catching it sooner. It should be fixed by https://github.com/NREL/api-umbrella/commit/ece75d456aa0a3e4e78fc03e4d880c3a9c65b16a I'll try to get a v0.14.1 release packaged up this week with this in it.

**Comment by GUI** [comment]
v0.14.1 has been released with this fix in it. Thanks again for reporting this issue!
