### ISSUE TITLE
Github auth callback URL?

### ISSUE THREAD

**Issue by brylie** [NREL/api-umbrella#46]
I am trying to configure Github authentication strategy. On the Github OAuth Application Settings page, there is a field for `Authorization callback URL`. What value should I put here?

* \<example.com\>/what/callback/url

**Comment by bragan** [comment]
I just opened another issue before finding this one about the same topic: https://github.com/NREL/api-umbrella/issues/88

It appears i am having the exact same problem. Are there any suggestions for a fix?

**Comment by GUI** [comment]
There was a bug in our GitHub authentication handling. It's now fixed in master of api-umbrella-web. This will be part of our next package release (version 0.7), but that's not yet scheduled. If you'd like the fixed now, you can deploy the api-umbrella-web component from master. See [Deploying From Git](http://nrel.github.io/api-umbrella/docs/deployment/) for further details.

**Comment by GUI** [comment]
Since this should be fixed in master, I'm going to go ahead and close this, so we can keep better track of which issues are resolved or not in our milestones.

**Comment by brylie** [comment]
Thanks GUI! :)

**Comment by GUI** [comment]
FYI: This fix is included in the [new v0.7 packages](https://github.com/NREL/api-umbrella/blob/master/CHANGELOG.md#070--2015-02-08) (along with other good stuff). Thanks for brining this to our attention!

**Comment by brylie** [comment]
@GUI, when will this fix be released? We are still [experiencing](https://github.com/apinf/api-umbrella-dashboard/issues/535#issuecomment-150233964) of this issue.
