### ISSUE TITLE
Github auth "invalid credentials"

### ISSUE THREAD

**Issue by bragan** [NREL/api-umbrella#88]
I have api-umbrella up and running and now trying to configure admin auth.

I have the yaml file configured correctly as far as i can tell and also have added the app to github as shown on the api-umbrella wiki.
web:
  admin:
    initial_superusers:
      - <email>
    auth_strategies:
      github:
        client_id: <id>
        client_secret: <secret>

When I click login with Github It directs me to the Github login page and I then get redirected to the callback url which takes me to an error page:
"We're sorry, but something went wrong.
We've been notified about this issue and we'll take a look at it shortly."

If i reload the page it sends me  back to the api-umbrella login page which has this error message:
Could not authenticate you from GitHub because "Invalid credentials".

**Comment by GUI** [comment]
Sorry for the delay. I think I've discovered the underlying bug in our GitHub authentication handling. This should be fixed in master of the api-umbrella-web component. This will be included in our next package release (version 0.7), but that's currently unscheduled. If you'd like to deploy the changes now, you can do so by deploying the api-umbrella-web component from master. See [Deploying From Git](http://nrel.github.io/api-umbrella/docs/deployment/) for further instructions on that.

**Comment by GUI** [comment]
Since this should be fixed in master, I'm going to go ahead and close this, so we can keep better track of which issues are resolved or not in our milestones.
