### ISSUE TITLE
supervisord

### ISSUE THREAD

**Issue by dmolina-ot** [NREL/api-umbrella#93]
Hello,
I'am trying to understand the process of start up. 
Which is the responsability or functionality of the supervisord?

Thanks

**Comment by GUI** [comment]
[supervisord](http://supervisord.org) is a process manager. It's role is to run the internal dependencies for API Umbrella (you can see the [diagrams](http://nrel.github.io/api-umbrella/docs/architecture/) for a sense of the dependencies). We depend on a number of other open source components, so this allows you to just run the "api-umbrella" process, but behind the scenes we use supervisord to spin up those other dependencies. Aside from spinning up the processes, since supervsiord is a process manager/supervisord/montioring tool, the other thing supervisord does is ensure that they keep running (so if a process ever crashes, it'll start it back up again).

Does that make sense and answer your question? Let me know if not.

**Comment by imi-apimanager-test** [comment]
Then nodejs /opt/api-umbrella/bin/api-umbrella starts the supervisord, and is the supervisor which starts nginx, mongodb, elastichsearch, redis, varnish, ...?

**Comment by dmolina-ot** [comment]
Then nodejs /opt/api-umbrella/bin/api-umbrella starts the supervisord, and is the supervisor which starts nginx, mongodb, elastichsearch, redis, varnish, ...?

**Comment by GUI** [comment]
Yes, the `bin/api-umbrella` script is responsible for reading the API Umbrella configuration, then writing the various config files for the other processes (for example, writing out the supervsiord.conf file, nginx.conf files, etc), and then finally kicking off supervsiord which actually runs all the processes. So while the `bin/api-umbrella` script is written in Node.js, there's nothing particularly "Node-y" about what it does--it's basically just a script to bootstrap our environment and then run the sub-processes via supervsiord.

**Comment by GUI** [comment]
I'm going to close this issue, but feel free to re-open if you have any further questions about how we use supervisord.
