### ISSUE TITLE
Admin API Token Issue

### ISSUE THREAD

**Issue by mtanvir21** [NREL/api-umbrella#95]
Hi, I've noticed that when you're on the Edit Admin page for the first admin account that was created, it doesn't show the admin API token. However, if you login with admin accounts that were created after the initial admin account this is not an issue. Any idea why this is happening?

**Comment by GUI** [comment]
The admin authentication tokens are only shown for your own admin account. So you must be logged in under an admin account to view its authentication token. Does that explain the behavior you're seeing? And does that make sense? The reasoning behind this is that you should only have access to your own admin token, and not tokens for other admins, or otherwise you could impersonate them. But let us know if you think this should behave differently.

**Comment by mtanvir21** [comment]
Thanks for the reply, but I think I didn't ask my question clearly, so I apologize for that. So the first admin account I created, let's just call it account1@email.com. When I log into the admin portal with this account, I cannot view the admin API token for account1@email.com. However, when I log in with accounts that were created after this account, let's call them account2@email.com and account3@email.com, I can view the admin tokens. So if I log in with account2@email.com I can view the admin API token for account2@email.com. Everything also works with account3@email.com. It's just that I cannot view the admin API token for account1@email.com while logged in as account1@gmail.com. Does that help out?

**Comment by GUI** [comment]
Ah, sorry this reply totally slipped past me. This makes sense and is indeed a bug. It should be fixed in master now so that the initial superuser accounts also have this auth token. This will be part of the v0.9 release.

Apologies again for not noticing this sooner and for the super-long delay for a fix!

cc @brylie
