### ISSUE TITLE
Header Rewriting

### ISSUE THREAD

**Issue by darylrobbins** [NREL/api-umbrella#96]
The admin web ui mentions "Modify the incoming request's URL or headers before passing it to the backend." under Advanced Requests Rewriting, but there does not seem to be any way to rewrite headers. Essentially what I am trying to accomplish is to let my backend know whether the original request was via http or https. My AWS Elastic Load Balancer (ELB) conveniently adds a x-forwarded-proto header to let me know but this information gets lost when the request travels through the second ELB for the backend service since all traffic is send via http.

**Comment by darylrobbins** [comment]
Please see: https://github.com/NREL/api-umbrella-gatekeeper/pull/7

**Comment by GUI** [comment]
Just to double check I understand this correctly, this is primarily to rename an existing header to another field, since the second ELB wipes out the original header? Because API Umbrella should pass along the original `X-Forwarded-Proto` header as-is, but it sounds like the second ELB backend is then overwriting that original value, is that correct? Ideally, you could setup the ELB to trust these forwarded headers from certain sources, but since I don't think that's possible, I can definitely see how renaming this to an alternative field would be useful.

And thanks for the PR! I just have a couple comments I'll leave over there.

**Comment by darylrobbins** [comment]
Yes, your understanding is correct. Unfortunately, there is no way to trust header values in an ELB, so you are correct they need to be saved with a different name. We will have one ELB in front of our API umbrella nodes and then one internal ELB in front of the backend nodes. This allows AWS to do auto healing and simplifies scaling significantly.

**Comment by GUI** [comment]
This has been released as part of the [new v0.7 packages](https://github.com/NREL/api-umbrella/blob/master/CHANGELOG.md#070--2015-02-08). Thanks for implementing this new feature!
