### ISSUE TITLE
Cannot Unset Restrict Access to IPs after Setting It

### ISSUE THREAD

**Issue by darylrobbins** [NREL/api-umbrella#97]
When an API user is first created in the web interface, their allowed_ips value is omitted entirely, granting them access from any IP.  However, after setting a value for this field and then later clearing it, the value in mongodb is set to `"allowed_ips" : [ "" ]`, which means they are granted access from no IP address. This is inconsistent with the default behaviour for not specifying a value for this field.

**Comment by GUI** [comment]
Ah, yeah, this is a bug with the allowed IPs and referrers. It's fixed in master and will be part of the v0.7 package release. Sorry for the issue!

I thought I was going to get the v0.7 packages released last week, but I'm aiming for the end of this week instead. If you don't want to wait for the fix, you can [deploy master](http://nrel.github.io/api-umbrella/docs/deployment/) on top of your existing install, but waiting for the packages may be easier.

And just for reference, here's the details from when this issue originally got fixed.
https://github.com/18F/api.data.gov/issues/155
https://github.com/NREL/api-umbrella-web/commit/92f5ed7214310335eb488e301ccfc7ce54c34941

**Comment by darylrobbins** [comment]
Thanks. I did a search before raising the bug but didn't notice that one since the title was referring to the referrer. Is there a way to build a custom package from the source instead? This is one thing I haven't been able to figure out how to do yet.

**Comment by GUI** [comment]
This has been released as part of the [new v0.7 packages](https://github.com/NREL/api-umbrella/blob/master/CHANGELOG.md#070--2015-02-08). Thank you very much for your contributions!

**Comment by darylrobbins** [comment]
Thanks! Looking forward to giving the new version a try.
